# Generated by Django 3.2 on 2021-07-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(default='content', max_length=250),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.TextField(),
        ),
    ]
